### ISSUE TITLE
Pre-compile all regexs as constants

### ISSUE THREAD

**Issue by dhowe** [dhowe/rita2js#14]

**Comment by Real-John-Cheung** [comment]
list of not pre-compiled regex

- [ ] `config/webpack.node.js`

- [ ] `src/analyzer.js line62`

- [ ] `src/grammar.js line45 note: have function inside`

- [ ] `src/lexicon.js line372;line381;line233;line142`

- [ ] `src/markov.js line110`

- [ ] `src/riscript.js line138;line168;line183;line198;`

- [ ] `src/tokenizer line15;line51-88;line98-100`
