### ISSUE TITLE
Center buttons in KWIC example

### ISSUE THREAD

**Issue by dhowe** [dhowe/rita2js#29]
- [ ] rita2js/examples/dom/KWICmodel/  (ready)
- [ ] rita2js/examples/p5/KWICmodel (need to do #25 first)

Also great if we can do some simple css styling to make the buttons and text look better

**Comment by Real-John-Cheung** [comment]
part1 should be solved with pull request _issue#29part1_
part2 should be solved with pull request _issue#25_ in commit _finishKWICmodel_

**Comment by dhowe** [comment]
thanks, I will check them over and merge if all ok

when you mention another issue, just use `#34` -> #34

then an automatic link is created
