### ISSUE TITLE
Finish examples updates

### ISSUE THREAD

**Issue by dhowe** [dhowe/rita2js#35]
General
--------
Use setTimeout() rather than setInterval()  (see code)
Use === or !== rather than == or !=

Rhymes / Markov / Grammar all good

**KWICmodel**
--------
- [ ] Redo using p5's createButton() function [p5]
- [ ] Match layout in dom - button row is center-aligned on red word [p5]

**Analysis**
--------
- [ ] Redo with new class style: 'class Bubble { ... ' [p5]
- [ ] Fix vertical alignment for large/small bubbles [dom]

![image](https://user-images.githubusercontent.com/737638/90619202-84fbc480-e243-11ea-8cdf-a1564e7fd91d.png)

**Comment by Real-John-Cheung** [comment]
see pull request #38
