### ISSUE TITLE
articlize() in RiScript seems to act weirdly inside grammar

### ISSUE THREAD

**Issue by Real-John-Cheung** [dhowe/rita2js#43]
e.g 
`toy.articlize()` will return `toya`
`man.articlize()` will return `mana`

**Comment by Real-John-Cheung** [comment]
- [x] Rita.Riscript.articlize() -> no problem

- [x] Grammar.expend()

- [ ] Rita.Riscript.evaluate()

**Comment by dhowe** [comment]
Can you create a test case that shows the problem? /rita2js/issues/known-issues.js is a good place for this

**Comment by Real-John-Cheung** [comment]
@dhowe I think I found the reason... 
it need to be '(toy).articlize()', the word needs to be in round brackets...

**Comment by dhowe** [comment]
correct, closing... unless you can convince me there is a need for something like `word.transform()`
