### ISSUE TITLE
Add documentation for RiTa.evaluate() and RiTa.addTransform (link to README#riscript)

### ISSUE THREAD

**Issue by Real-John-Cheung** [dhowe/rita2js#60]
In
`src/rita.js` line19

**Comment by dhowe** [comment]
in the future, please link directly to the line of code in github, e.g. [this line](https://github.com/dhowe/rita2js/blob/master/src/rita.js#L19)

**Comment by Real-John-Cheung** [comment]
done (the entries have been added to the reference), ready to close
