### ISSUE TITLE
Add tests for Grammar.fromJSON/toJSON

### ISSUE THREAD

**Issue by dhowe** [dhowe/rita2js#72]
TEST:
1. Create a grammar
2. Save it as a String with toJSON()
3. Then reload it with fromJSON() and make sure it is the same as the original

Then make sure both are correctly documented in the reference

**Comment by Real-John-Cheung** [comment]
- [ ] write test

- [ ] write document

**Comment by Real-John-Cheung** [comment]
ready to close
